setopt HIST_IGNORE_ALL_DUPS
bindkey -e
source ~/.config/zsh/alias.zsh
source ~/.config/zsh/keybindings.zsh
source ~/.config/zsh/zim.zsh
source ~/.config/zsh/prompt.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/env.zsh
source ~/.config/zsh/key-bindings.zsh
source ~/.config/zsh/completion.zsh
export PATH=~/.npm-global/bin:$PATH
